### PR TITLE
Automate setup on known HPC clusters

### PR DESCRIPTION
**Pull request by johnomotani**
Provide scripts that set up a working configuration for `moment_kinetics` on known HPC clusters (currently ARCHER2 and Marconi).

A wrapper script `machines/machine_setup.sh` prompts the user for some options (most of which have sensible defaults) and runs the complete setup: downloading Julia (if requested); setting up `JULIA_DEPOT_PATH` (necessary on ARCHER2 as the home directory is not accessible from the compute nodes); setting up HDF5 and MPI; and (if desired) launching a job to precompile, creating `moment_kinetics.so`.

The sub-steps run by `machine_setup.sh` can be run individually if that is useful, they are described in an [Advanced usage section in the docs](https://mabarnes.github.io/moment_kinetics/previews/PR100/machine_setup/#Advanced-usage).

Also includes a script `submit_run.sh` that submits a simulation and linked post-processing job, using template submission scripts. Run parameters (number of nodes, time limit, etc.) have defaults stored in `LocalPreferences.toml` (these can be set when running the setup, and changed by editing `LocalPreferences.toml`), but can be altered with command-line options to the script. The options are only single-letter flags, because I found the function to parse those with Bash and long option names seemed a lot more complicated - but they are documented in the help printed by `submit_run.sh -h`.

I made this PR because I got parallel I/O working on ARCHER2 and wanted to document the process. We've found having some cluster-specific setup scripts useful with BOUT++, so I thought they would be convenient for `moment_kinetics`.
Once I'd got ARCHER2 working I had another go at getting parallel I/O to work on Marconi, and managed it. Not sure what I did differently this time than the last time I tried and failed! Requires compiling HDF5 from the source code - a script is included that takes care of that as part of the automated setup.

The scripts are mostly a combination of bash and Julia, to avoid needing to install or setup any packages in order to use them (other than the Julia that is being set up by the script itself). The one exception is a Python script that is used to get the link to download Julia binaries. The best way to download the latest stable version of Julia (or any other version, there's a prompt asking if you want to pick one) involved parsing a json file that's provided by the Julia organisation listing some info for all the released versions. Python seemed like the most portable straightforward way to do that parsing. The Python script has no dependencies outside the core Python install though, so any Python>=3.6 should be enough to run it.

### CODE REVIEW

**Comment by johnomotani** [comment]
@mabarnes while setting up Marconi, I found that running post-processing just produced blank plots (weirdly only when I ran by submitting a job, not when running interactively on the login nodes). Sounds like the same symptoms you mentioned you had on macOS, although I don't know if it's the same bug/problem - I managed to 'fix' it by moving the call to `pyplot()` (see commit e0da4d0). I don't understand why this made a difference, and it made one of the CI jobs fail (my best guess is that it increased the memory usage slightly and made the CI server run out of RAM), so I had to restrict so the `pyplot()` call is only made when running in serial (which post-processing should always be) in 21c2b17.

**Comment by mrhardman** [comment]
Running the post processing, I find the following error:

ERROR: LoadError: MethodError: no method matching load_distributed_charged_pdf_slice(::Tuple{String}, ::Tuple{Int64}, ::Colon, ::Int64, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate; z=1)
Closest candidates are:
  load_distributed_charged_pdf_slice(::Tuple, ::Tuple, ::Any, ::Int64, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate; is, ir, iz, ivperp, ivpa) at /*/moment_kinetics/src/load_data.jl:632 got unsupported keyword argument "z"
Stacktrace:
 [1] kwerr(::NamedTuple{(:z,), Tuple{Int64}}, ::Function, ::Tuple{String}, ::Tuple{Int64}, ::Function, ::Int64, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate, ::moment_kinetics.coordinates.coordinate)
   @ Base ./error.jl:165
 [2] plot_charged_pdf_2D_at_wall(run_name::Tuple{String}, run_name_label::String, r_global::moment_kinetics.coordinates.coordinate, z_global::moment_kinetics.coordinates.coordinate, nblocks::Tuple{Int64}, n_ion_species::Int64, r::moment_kinetics.coordinates.coordinate, z::moment_kinetics.coordinates.coordinate, vperp::moment_kinetics.coordinates.coordinate, vpa::moment_kinetics.coordinates.coordinate, ntime::Int64)
   @ moment_kinetics.post_processing /*/moment_kinetics/src/post_processing.jl:3486
   
   @johnomotani If you are exploring writing a new diagnostic script, it is possible to revert the old diagnostic script to a working state (pre multi simulation support?) for my physics study?

**Comment by johnomotani** [comment]
Hi Michael,

I realised looking at the 'fix' that a couple of the plots (over z-vpa or z-r) aren't supported at the moment.
You could try checking out the src/post_processing.jl file from your branch before the merge - I'm not sure if it would work or not, although I don't think we would have removed anything from the output files so it might be OK.

In the new post-processing, I've re-written (partially) the data-loading, and the function there can load an arbitrary slice, so I'm more inclined to implement the wall-plots in there rather than spend time adding more stuff to get the missing plots implemented in the 'old' (but post-merge) routines.

Let me know if the missing plots are important - I could put up at least a 'work-in-progress' version of the new routines as a draft PR, but I'd need to tidy up my commit history a bit to do that...

John

________________________________

**Comment by mrhardman** [comment]
A further bug when post processing, after applying the fix for the 2D plots:

ERROR: LoadError: MethodError: no method matching manufactured_solutions(::Float64, ::Float64, ::String, ::String, ::moment_kinetics.input_structs.geometry_input, ::moment_kinetics.input_structs.species_composition, ::Int64)
Closest candidates are:
  manufactured_solutions(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, !Matched::Any, !Matched::Any) at /mnt/lustre/a2fs-work2/work/e281/e281/hardm281/moment_kinetics_2/src/manufactured_solns.jl:310
Stacktrace:
 [1] analyze_and_plot_data(prefix::String; run_index::Nothing)
   @ moment_kinetics.post_processing /mnt/lustre/a2fs-work2/work/e281/e281/hardm281/moment_kinetics_2/src/post_processing.jl:1071
 [2] analyze_and_plot_data(prefix::String)
   @ moment_kinetics.post_processing /mnt/lustre/a2fs-work2/work/e281/e281/hardm281/moment_kinetics_2/src/post_processing.jl:383
 [3] top-level scope
   @ /mnt/lustre/a2fs-work2/work/e281/e281/hardm281/moment_kinetics_2/run_post_processing.jl:7
in expression starting at /mnt/lustre/a2fs-work2/work/e281/e281/hardm281/moment_kinetics_2/run_post_processing.jl:1

**Comment by johnomotani** [comment]
@mrhardman should be fixed now. I think the errors were introduced in #99 when I changed how the manufactured solutions input options were handled - sorry about that, I should have tested after the update.

**Comment by mrhardman** [comment]
Following the latest postprocessing fix, I confirm that I have now successfully run a 1D1V MMS test with a single ion species on with this branch.

**Comment by johnomotani** [comment]
In that case lets call this done!

We can always have small PRs with more bug-fixes anyway.

**Comment by mrhardman** [comment]
I am going to go on to the 2D1V MMS tests as these are closest to the runs that I want  to perform, as well as push the example refactored MMS input files to the repo. What do you think is best to do with the now unsupported input files in this PR? I would like to decide that before merging.

**Comment by johnomotani** [comment]
Ah, the input files should really have been updated in #99... I think I was meaning to go back and do that before merging but forgot. It would make sense to update the rest of the input files in this PR now that you've started - I don't think there's any particular rush (just my urge to push the 'merge' button)!

**Comment by mrhardman** [comment]
I am also open to reducing the number of input files that we store so that we can increase on the diversity of run types without overloading the repo. It would be good to also have your standard input files recorded here, for example.

**Comment by johnomotani** [comment]
Mine are under the `examples/` subdirectory. The slight wrinkle is that at the moment the CI tries to check that all the input files under `examples/` run for a couple of timesteps - a few issues: if the input file asks for distributed-memory MPI it will fail because it's running in serial; if the run is actually large, it will probably run out of memory; if we have too many input files in there, the CI job will take a long time, which is a bit of a waste of resources.

There's an easy solution to this - we give a list of the input files that should be checked (e.g. a 'small' one of each type). I didn't do that to start with, hoping to avoid having to maintain the list, but it seems like the best way now.

**Comment by mrhardman** [comment]
I confirm that the 2D1V MMS test runs successfully, including post processing. I just committed the form of that input .toml to the repo.

**Comment by mrhardman** [comment]
A new bug: post processing a run that uses the distributed memory MPI triggers MPI abort

post-processing runs/2D-wall_evolve_nel_r_32_z_32_vpa_16_vperp_1_diss_mpi/ Tue  8 Aug 10:31:12 BST 2023
Initializing the post-processing input options...done.
Analyzing fields data...done.
Plotting fields data...
done.
ERROR: You must choose global number of processes to be an integer multiple of the number of

                     nblocks = (r_nelement_global/r_nelement_local)*(z_nelement_global/z_nelement_local)
MPICH ERROR [Rank 0] [job id ] [Tue Aug  8 10:36:02 2023] [dvn01] - Abort(1) (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

Presumably this is because the postprocessing now carry out much of the setup in the same way as the main code.

**Pull request merged**
